### ISSUE TITLE
Please add an example

### ISSUE THREAD

**Issue by hfinkel** [kokkos/kokkos-fortran-interop#1]
I have some users who might be interested in this, and it would be great if there were an example in the README or in a simple source file to give potential users some idea of how this might help them.

**Comment by womeld** [comment]
@hfinkel  here is one example: https://github.com/kokkos/kokkos-fortran-interop/pull/8/files

Let me know if you had something more than that in mind. I plan to also add an example using the kokkos_allocate path as well.

**Comment by womeld** [comment]
Closing this for now. Feel free to make a new issue if you have anything in mind.
