### ISSUE TITLE
Does FLCI support AMD?

### ISSUE THREAD

**Issue by jsboer** [kokkos/kokkos-fortran-interop#64]
Hi, I find it is not have information about hip, does FLCL support hip? If so, how to build with hip? And dose the use is same as the following shows? 
https://kokkos.org/kokkos-core-wiki/usecases/Kokkos-Fortran-Interoperability.html#/:~:text=of%20contents%20sidebar-,Fortran%20Interop%20Use%20Case,-%23

**Comment by dalg24** [comment]
It looks like currently it does not
https://github.com/kokkos/kokkos-fortran-interop/blob/967d3de9e52bb11d203c76cd8a4c9426c8c8df25/src/flcl-cxx.hpp#L59-L63
But that it should be easy to extend.

**Comment by jsboer** [comment]
Okay, thank you!
